ARG IMAGE=node:20-buster-slim
ARG NGINX_IMAGE=nginx:1.27.1

# COMMON
FROM ${IMAGE} as build
WORKDIR /app
COPY . .

# Install dependencies.
RUN npm i 

FROM build as dev
CMD [ "npm", "run", "dev", "--", "--host"  ]

FROM ${NGINX_IMAGE} as prod
COPY --from=build /app/client/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]